### ISSUE TITLE
Incompatible with "options_ui": {"open_in_tab": false

### ISSUE THREAD

**Issue by jesteves** [jusio/storage-area-explorer#25]
Although the explorer works fine with in a separate tab, with the [new (and now recommended) option `"options_ui": {"open_in_tab": false`](https://developer.chrome.com/extensions/optionsV2), it seems to enter an infinite loop.

To reproduce, open the (new) options modal for an an extension, [inspect it](http://stackoverflow.com/a/31088464) and click on explorer tab in devtools.

**Comment by jusio** [comment]
there are quite a few cases when storage explorer will go into infinite loop (because it simply doesn't know what it is inspecting), other examples are inspecting the devtools extensions, chrome internal pages, special pages protected by google and etc. 

As workaround you can always simply inspect extension background page instead of the option page, it will give you and overview of both localStorage and chrome.storage.

**Comment by jesteves** [comment]
Sorry, but I'm afraid it didn't worked around in may case... For starters, my extension doesn't have a background page (yet...), but even adding one for the sake of testing, it entered a loop. :-(

> _For now I'm just fine with having the options page on a separate tab until release..._

**Comment by jusio** [comment]
How do you inspect background page? I've just tried going to chrome://extensions, navigating to one of the extensions and clicked Inspect views: background_page, and then I switch to storage explorer tab and it works somehow. Do you follow the same steps, or you do something differently?

**Comment by jesteves** [comment]
I did exactly what you describe.

Let me see if I can share with you what I have, and how I see it...

**Comment by jesteves** [comment]
It turns out I probably _didn't_ do what you meant.

In chrome://extensions → the extension → In "inspect views: background.html"  (which, btw in Spanish reads "analizar vistas", that is "analyze views")

*  if you left-click on background.html → window pops-up → inspect → devtools open → the explorer works fine.

*  If, on the other hand, you right-click on background.html → select "inspect" from context menu → devtools open → the explorer enters a loop.

**Comment by jusio** [comment]
Ah, ok now I get it. If you use right click, it is just trying to inspect chrome://extensions page, which isn't allowed by chrome. Left click is the right way to inspect background page. So at least it isn't some new combination I have to handle in specific way:) thanks for the report


> (which, btw in Spanish reads "analizar vistas", that is "analyze views")

Ouch, I'm not native english speaker myself, so it is very familiar problem to me.

**Comment by jesteves** [comment]
Hello @jusio ,

Just to let you know that apparently the behaviour reported is not longer affecting Storage Explorer as per Chrome version  56.0.2924.87 (64-bit).

I've just tested it again (that is, I accidentally found myself inspecting the Options page of my extension while in the [new] modal view) and the loop is gone!

So I'm marking this issue as closed.

Thanks a lot,

Julián

**Comment by jusio** [comment]
I love it when issues solves itself:D thanks for report and good luck with your project!
